### ISSUE TITLE
label:enhancement Compile & Run

### ISSUE THREAD

**Issue by alobaid** [christoomey/vim-run-interactive#5]
It would be great if you could add compile and run for some of the most used languages like go, swift, rust etc.. depending on the file extension  so instead 
`nnoremap <Leader>cb :RunInInteractiveShell crystal build % --release && ./%:r<space>  `
`nnoremap <Leader>rs :RunInInteractiveShell rustc % && ./%:r<space> `
I would just use <Leader>run  as a wild card for any language

**Comment by christoomey** [comment]
Hey @alobaid, thanks for suggestion. In the end, I think this is outside the scope of this plugin. The goal with this plugin was just to provide the machinery to support running commands interactively. That said, I think it would be reasonably straightforward to add this yourself, still using `RunInInteractiveShell`. I have [very similar code in my vim-tmux-runner plugin](https://github.com/christoomey/vim-tmux-runner/blob/5efb5197bbcd8e32e9868a96466f7674053e69b4/plugin/vim-tmux-runner.vim#L407-L432):

``` vim
function! s:SendFileViaVtr(ensure_pane)
    let runners = s:CurrentFiletypeRunners()
    if has_key(runners, &filetype)
        write
        let runner = runners[&filetype]
        let local_file_path = expand('%')
        let run_command = substitute(runner, '{file}', local_file_path, 'g')
        call VtrSendCommand(run_command, a:ensure_pane)
    else
        echoerr 'Unable to determine runner'
    endif
endfunction

function! s:CurrentFiletypeRunners()
    let default_runners = {
            \ 'ruby': 'ruby {file}',
            \ 'javascript': 'node {file}',
            \ 'python': 'python {file}',
            \ 'sh': 'sh {file}'
            \ }
    if exists("g:vtr_filetype_runner_overrides")
      return extend(copy(default_runners), g:vtr_filetype_runner_overrides)
    else
      return default_runners
    endif
endfunction
```

You could modify / extend this to work for your needs, without the need to update this plugin directly. I'm going to close this now as this is not something I plan to support in the plugin core, but hopefully the above will help you get to a work solution for your use case.

**Comment by alobaid** [comment]
Thanks a lot that more than fin :)
